name: Playwright Tests
on:
  deployment_status:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: corepack enable && pnpm install

      - name: Run Playwright tests
        run: pnpm test:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
          HOME: /root

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
